name: 清理Actions

on:
  workflow_dispatch:
    inputs:
      retain_days:
        description: '保留最近多少天的运行记录'
        required: true
        default: '30'

  # 如果你以后要定期执行，可以取消注释下面：
  # schedule:
  #   - cron: 0 3 */3 * *

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.REPO_TOKEN }}
          repository: ${{ github.repository }}
          keep_minimum_runs: 0
          retain_days: ${{ github.event.inputs.retain_days }}
